"""create_initial_tables

Revision ID: c362b7867063
Revises: 
Create Date: 2026-08-19 11:58:20.713247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c362b7867063'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('subjects', 'name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('subjects', 'description',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_subjects_id'), table_name='subjects')
    op.drop_constraint(op.f('subjects_ibfk_1'), 'subjects', type_='foreignkey')
    op.create_foreign_key(None, 'subjects', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=False)
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'name')
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.create_foreign_key(op.f('subjects_ibfk_1'), 'subjects', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_subjects_id'), 'subjects', ['id'], unique=False)
    op.alter_column('subjects', 'description',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('subjects', 'name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('subjects', 'created_at')
    # ### end Alembic commands ###
